# -*- coding: utf-8 -*-
"""cad3d.core —— 核心基础组件包。"""

from cad3d.core.config import (
    _CFG_NOTES,
    _JRT_BLEND_R,
    _JRT_R_MIN,
    _JRT_R_STEP,
    _USER_CFG,
    SCHEMA_VERSION,
    _cfg,
    _cfg_int,
    _cfg_num,
    _import_module_from_path,
    _load_user_config,
    _note,
)
from cad3d.core.constants import (
    _CX_LINK_END_OFF,
    _JT_LINK_FALLBACK,
    _LAYER_DEFS,
    _LAYER_DISTS,
    _LINK_OFFSETS,
    _LINK_OFFSETS_RAW,
    _NX_LAYER_START,
    _ZMODE_DEFS,
    _ZMODE_FALLBACK,
    BOOL_OPTS,
    CHAIN_TOL,
    COMP_PREFIX,
    DEFAULT_JRT,
    DEFAULT_STD_RULE,
    DIALOG_GROUPS,
    DIR_OPTS,
    DYNAMIC_START,
    FEATURE_PREFIX,
    JRT_FIELDS,
    JRT_FROM_TOP,
    JT_LINK_DEFAULT,
    JT_LINK_MODES,
    JT_LINK_OPTS,
    LAYER_CODES,
    LAYER_SEL_OPTS,
    LAYER_TABLE,
    LINK_RULES,
    LOOP_TOL,
    MANAGED_MAX,
    MANAGED_MIN,
    REF_LAYER_TABLE,
    SCRIPT_VERSION,
    STD_MAX_ANCHORS,
    STDPARTS_DIRNAME,
    TARGET_CODE,
    ZMODE_OPTS,
    assign_layers,
)
from cad3d.core.logging import Log, _fmt_num
from cad3d.core.paths import (
    ROOT_DIR,
    _fresh_dlx_path,
    _json_path,
    _logs_dir,
    _temp_dlx_path,
    resolve_dxf_path,
    script_dir,
    stdparts_dir,
)
from cad3d.core.state import (
    _cx_link_values,
    _jt_link_values,
    _name_list,
    default_params,
    derive_linked,
    jrt_with_memory,
    jt_mode_with_memory,
    load_state,
    merge_jrt,
    merge_params,
    save_state,
)
